# config.yaml
ppo:
  learning_rate: 0.0003
  n_steps: 1000
  batch_size: 64
  n_epochs: 1
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
policy_kwargs:
  net_arch: [64, 64]  # Policy network architecture
env_config:
  config_file: 'path/to/your/env/config.yaml'
  sim_params: {}  # Add necessary simulation parameters
  physics_engine: 'your_physics_engine'
  sim_device: 'cpu'
  render: False